import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerate sidebars from the docs folder structure
const sidebars: SidebarsConfig = {








  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
